[package]
name = "rustbelt"
version = "0.0.1"
authors = ["Bo Du <bokwandu@gmail.com>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "1.0"
volatile = "0.1.0"
spin = "0.4.5"
multiboot2 = "0.1.0"
